# Generated by Django 6.0.7 on 2026-07-28 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy_cms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='note',
            name='content_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='studybuddy_cms.contentitem'),
        ),
        migrations.AddField(
            model_name='note',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags.', max_length=255),
        ),
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['subject', 'owner'], name='studybuddy__subject_567d94_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['tags'], name='studybuddy__tags_705ef2_idx'),
        ),
    ]
