# Generated by Django 6.0.7 on 2026-07-29 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy_cms', '0003_savedflashcards_savedquiz_savedsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedquiz',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studybuddy_cms.subject'),
        ),
    ]
