# Generated by Django 6.0.7 on 2026-07-29 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy_cms', '0004_savedquiz_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedflashcards',
            old_name='title',
            new_name='flashcard_title',
        ),
        migrations.RenameField(
            model_name='savedflashcards',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='savedquiz',
            old_name='title',
            new_name='quiz_title',
        ),
        migrations.RenameField(
            model_name='savedquiz',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='savedsummary',
            old_name='title',
            new_name='summary_title',
        ),
        migrations.RenameField(
            model_name='savedsummary',
            old_name='owner',
            new_name='user',
        ),
    ]
