# Generated by Django 6.0.7 on 2026-07-29 02:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy_quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='generatedquiz',
            name='studybuddy__user_id_a0c9dd_idx',
        ),
        migrations.RemoveIndex(
            model_name='quizresult',
            name='studybuddy__user_id_60a7db_idx',
        ),
        migrations.RenameField(
            model_name='quizresult',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='quizresult',
            old_name='quiz_title',
            new_name='title',
        ),
        migrations.AddIndex(
            model_name='quizresult',
            index=models.Index(fields=['owner', '-created_at'], name='studybuddy__owner_i_5279b9_idx'),
        ),
        migrations.DeleteModel(
            name='GeneratedQuiz',
        ),
    ]
