# Generated by Django 6.0.7 on 2026-07-29 03:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy_quiz', '0002_remove_generatedquiz_studybuddy__user_id_a0c9dd_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quizresult',
            name='studybuddy__owner_i_5279b9_idx',
        ),
        migrations.RenameField(
            model_name='quizresult',
            old_name='title',
            new_name='quiz_title',
        ),
        migrations.RenameField(
            model_name='quizresult',
            old_name='owner',
            new_name='user',
        ),
        migrations.AddIndex(
            model_name='quizresult',
            index=models.Index(fields=['user', '-created_at'], name='studybuddy__user_id_60a7db_idx'),
        ),
    ]
